python  -m src.create_data
python  -m src.create_seq_data
python  -m src.dae_train
python  -m src.dae_inference
python  -m src.create_folds
#python  -m src.nn_train
python  -m src.nn_inference
python  -m src.catboost_model
python  -m src.merge